from __future__ import annotations

from pathlib import Path

from ..agent.schemas import ProjectConfig, ToolCall, ToolResult, ToolStatus


def run_paper_writer(call: ToolCall, config: ProjectConfig) -> ToolResult:
    artifact_dir = Path.cwd() / "artifacts"
    artifact_dir.mkdir(parents=True, exist_ok=True)
    output = artifact_dir / "pasnet_da_agent_table.tex"
    tex = r"""\begin{table}[t]
\centering
\caption{PASBench-DA workflow summary generated by MeteoAgent-DA.}
\label{tab:pasbench_da_workflow}
\begin{tabular}{llll}
\toprule
Task Type & Tool Evidence & Verifier & Post-training Signal \\
\midrule
Data query & split/stats inspection & path and count checks & SFT trajectory \\
Experiment planning & PASNet command generation & controlled args & preference pair \\
Result reasoning & RMSE/MAE summaries & metric parser & reward score \\
Paper writing & table/caption artifact & LaTeX lint & SFT trajectory \\
\bottomrule
\end{tabular}
\end{table}
"""
    output.write_text(tex, encoding="utf-8")

    paragraph = (
        "MeteoAgent-DA constrains the weather-agent problem to satellite data-assimilation research. "
        "Instead of answering broad weather questions from text alone, it grounds each response in "
        "PASNet-DA tools for data indexing, experiment construction, metric parsing, plotting, and "
        "paper artifact generation."
    )
    return ToolResult(
        name=call.name,
        status=ToolStatus.OK,
        summary="Generated a LaTeX workflow table and a paper-style result paragraph.",
        data={"paragraph": paragraph, "latex_table": str(output), "style": call.arguments.get("style", "ieee")},
        artifacts=[str(output)],
    )
